import './globals.css'
import Navbar from '../components/navbar'
import Subscribe from '../components/subscribe'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Grandmind Care',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Subscribe/>
        </body>
    </html>
  )
}
